name: "Windows build"
on: push
jobs:
  win-build:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: make build directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: configure
        working-directory: ${{github.workspace}}/build
        run: cmake -G Ninja ..
      - name: build
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config release
      - name: list files
        run: find ${{github.workspace}}/build
        shell: bash
