name: "Windows build"
on: push
jobs:
  win-build:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: make build directory
        run: cmake -E make_directory ${{github.workspace}}/build
      - name: configure
        working-directory: ${{github.workspace}}/build
        run: cmake -G Ninja --preset release ..
      - name: build
        working-directory: ${{github.workspace}}/build/Release
        run: cmake --build .
      - name: upload
        uses: actions/upload-artifact@v1
        with:
          name: nesl
          path: |
            ${{github.workspace}}/build/Release/nesl.exe
            README.md
            testing/*
