name: "Build"
on: push
jobs:
  win-build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v6
      - name: configure and build
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
          cmake -G Ninja --preset release -S . -B build/Release
          cmake --build build/Release
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: nesl-windows-x64
          path: ${{github.workspace}}/build/Release/nesl.exe

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: configure
        run: cmake -G Ninja --preset release -S . -B build/Release
      - name: build
        working-directory: ${{github.workspace}}/build/Release
        run: cmake --build .
      - name: run regression tests
        run: bash testing/run_tests.sh
      - name: upload
        uses: actions/upload-artifact@v6
        with:
          name: nesl-linux-x64
          path: ${{github.workspace}}/build/Release/nesl
